/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Id]
      ,[Text]
      ,[Date]
      ,[LikesCount]
      ,[PostId]
      ,[OwnerId]
      ,[OwnerName]
  FROM [BlogWebExam].[dbo].[Comments]
  SELECT TOP (1000) [Id]
      ,[Text]
      ,[Date]
      ,[LikesCount]
      ,[CommentId]
      ,[OwnerId]
      ,[OwnerName]
      ,[WhomId]
      ,[WhomName]
  FROM [BlogWebExam].[dbo].[CommentReply]
  SELECT TOP (1000) [Id]
      ,[UserId]
      ,[CommentId]
  FROM [BlogWebExam].[dbo].[LikedComment]
  SELECT TOP (1000) [Id]
      ,[UserId]
      ,[CommentReplyId]
  FROM [BlogWebExam].[dbo].[LikedCommentReply]